version: '3.7'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - db:/var/lib/mysql
  api:
    tty: true
    depends_on:
      - db
    image: koutafujise/keio_sfc_labo_web_api
    # image: keio_sfc_labo_web_api
    # build:
    #   context: ./api/
    #   dockerfile: Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./api:/app
    command: >
      bash -c 'rm -f /app/tmp/pids/server.pid &&
      rails server -b 0.0.0.0 &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed'
  front:
    image: koutafujise/keio_sfc_labo_web_front
    # image: keio_sfc_labo_web_front
    # build:
    #   context: ./front/
    #   dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "8000:3000"
volumes:
  db:
    driver: local
